### ISSUE TITLE
Transitions not working with home assistant

### ISSUE THREAD

**Issue by vmazmaz** [Aircoookie/WLED#630]
Hello,

First of all, I would like to thank you Air cookie for the phenomenal job you have been doing with WLED, it has been a game changer for DIY LED lighting. 
I have been trying to use transition times with Home Assistant (using the native integration) but I have not been successful, the state changes immediately, regardless of the `transition:` value. Am I missing something ?

Thank you !

**Comment by fishbone-git** [comment]
see #543

**Comment by vmazmaz** [comment]
In my case, the `transition:` parameter is ineffective, even inside of an automation.

**Comment by Aircoookie** [comment]
Hi and thank you for your kind words!

What home assistant version are you running? This should have been fixed in version 0.104.0 :)

**Comment by vmazmaz** [comment]
I upgraded to 0.140.0 and it is working now ! I still experience a brief flash a the beginning of the transition but I suspect it might not have anything to do with WLED but rather with the Circadian Lighting component I am using. Thanks !

**Comment by Aircoookie** [comment]
@vmazmaz great that it is working now! Does the flash also happen when you turn on the light with the web UI? If yes, it is most likely an issue with the signal level not being strong enough to reliably drive the LEDs. If that is the case, you could try adding a level shifter.
